using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using UnityEditor;

namespace NataneToon.Editor
{
    public static class NataneToonLocalization
    {
        private const string LANG_PREFS_KEY = "NataneToon_Language";
        private static int _language = -1; // -1 = uninitialized
        private static readonly Regex JapaneseTextRegex = new Regex("[ぁ-ゖァ-ヺ一-龯々ー]", RegexOptions.Compiled | RegexOptions.CultureInvariant);
        private static readonly Regex SuspiciousLocalizedTextRegex = new Regex("[�]|[ｦ-ﾟ]|\\?{2,}|遯", RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly Dictionary<string, string> JapaneseFallbackExact = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "=== Summary ===", "=== 概要 ===" },
            { "2nd Border", "2段目境界" },
            { "3rd Border", "3段目境界" },
            { "5 Eye States + Expression Overlay Support", "5つの目状態 + 表情オーバーレイ対応" },
            { "A", "A" },
            { "A Screen FX overlay quad was created, parented to the target camera, and assigned a new material asset.", "Screen FX オーバーレイ用の Quad を作成し、対象カメラの子にして新規マテリアルを割り当てました。" },
            { "Active Features", "有効機能" },
            { "Add All Natane Toon Materials", "Natane Toon の全マテリアルを追加" },
            { "Add Selected Materials", "選択中のマテリアルを追加" },
            { "Additional Textures (2nd-5th)", "追加テクスチャ (2nd-5th)" },
            { "Adds iris depth, limbal ring, sclera shading, and a cornea-like top highlight. Enable Realistic Eye first, then tune Iris Depth and Cornea controls.", "虹彩の奥行き、輪部リング、強膜シェーディング、角膜風の上部ハイライトを追加します。先にリアルな瞳を有効化し、その後で虹彩の奥行きと角膜設定を調整してください。" },
            { "Advanced combinations: SSS, MatCap, Specular, Rim Light", "高度な組み合わせ: SSS、MatCap、Specular、Rim Light" },
            { "Advanced", "詳細" },
            { "After conversion, Renderer references in the prefab will be automatically updated to new materials.", "変換後、Prefab 内の Renderer 参照は新しいマテリアルへ自動更新されます。" },
            { "Alpha Clip Threshold", "アルファクリップしきい値" },
            { "AO Intensity", "AO 強度" },
            { "AO Map", "AO マップ" },
            { "AO Settings", "AO 設定" },
            { "Apply Strength", "適用強度" },
            { "Are you sure you want to clear all variants from this collection?", "このコレクションからすべてのバリアントを削除しますか？" },
            { "Are you sure you want to delete the runtime prewarming script?", "ランタイム用プリウォームスクリプトを削除しますか？" },
            { "As Unlit", "Unlit として扱う" },
            { "Auto-Find Materials", "マテリアルを自動検出" },
            { "Auto-Fix All Issues", "すべて自動修正" },
            { "Auto-Fix Applied", "自動修正を適用" },
            { "Auto-Fix Complete", "自動修正完了" },
            { "Auto-Fix", "自動修正" },
            { "Automatically find and prewarm all Natane Toon materials in the project", "プロジェクト内の Natane Toon マテリアルを自動検出してプリウォームします" },
            { "Automatically prewarm shaders before building", "ビルド前にシェーダーを自動プリウォームします" },
            { "Auto-update References", "参照を自動更新" },
            { "Avatar/Prefab", "アバター/Prefab" },
            { "B", "B" },
            { "Background Color (HDR)", "背景色 (HDR)" },
            { "Background", "背景" },
            { "Base Texture", "ベーステクスチャ" },
            { "Base", "ベース" },
            { "Blend & Transparency", "ブレンドと透明" },
            { "Blend Mode", "ブレンドモード" },
            { "Blend Operation", "ブレンド演算" },
            { "Blend", "ブレンド" },
            { "Blocker Search Radius", "遮蔽物検索半径" },
            { "Blur", "ぼかし" },
            { "Blush", "チーク" },
            { "Both Toon Weight and PBR Weight are near zero. The base shading may become weaker than intended.", "Toon Weight と PBR Weight の両方がほぼ 0 です。ベースシェーディングが意図より弱くなる可能性があります。" },
            { "Bottom Color", "下側の色" },
            { "Bubble Brightness", "バブルの明るさ" },
            { "Bubble Effect", "バブルエフェクト" },
            { "Bubble Size", "バブルサイズ" },
            { "Camera Not Found", "カメラが見つかりません" },
            { "Cancel", "キャンセル" },
            { "Caustics Color (HDR)", "コースティクス色 (HDR)" },
            { "Caution", "注意" },
            { "Cel Shading Settings", "セルシェーディング設定" },
            { "Center Fill", "中央塗りつぶし" },
            { "Change Shader Type", "シェーダータイプ変更" },
            { "Change", "変更" },
            { "Changing the shader type may cause some current settings to be lost.\nContinue?", "シェーダータイプを変更すると、現在の設定の一部が失われる可能性があります。\n続行しますか？" },
            { "Choose a location to save the shader variant collection", "シェーダーバリアントコレクションの保存先を選択してください" },
            { "Clear Collection", "コレクションをクリア" },
            { "Clear List", "リストをクリア" },
            { "Close", "閉じる" },
            { "Collect Used Material Keywords Only", "使用中マテリアルのキーワードのみ収集" },
            { "Collect Variants", "バリアントを収集" },
            { "Collection cleared!", "コレクションをクリアしました。" },
            { "Collection saved!", "コレクションを保存しました。" },
            { "Color Mask", "カラーマスク" },
            { "Color Preservation & Enhancement", "色保持と強調" },
            { "Color", "色" },
            { "Common combinations: No features, Outline only, Emission only", "一般的な組み合わせ: 機能なし、アウトラインのみ、Emission のみ" },
            { "Comparison Function", "比較関数" },
            { "Complete!", "完了!" },
            { "Contrast", "コントラスト" },
            { "Controls inner mesh draw priority when using BlendShapes.", "BlendShape 使用時の内側メッシュ描画優先度を制御します。" },
            { "Conversion Mode", "変換モード" },
            { "Conversion Report", "変換レポート" },
            { "Convert All Materials", "全マテリアルを変換" },
            { "Convert Prefab Materials", "Prefab マテリアルを変換" },
            { "Convert", "変換" },
            { "Converting Materials", "マテリアル変換中" },
            { "Converting Prefab Materials", "Prefab マテリアル変換中" },
            { "Copy parameters to clipboard", "パラメータをクリップボードへコピー" },
            { "Copy", "コピー" },
            { "Cornea Fresnel", "角膜フレネル" },
            { "Cornea Smoothness", "角膜の滑らかさ" },
            { "Cornea Spec Color (HDR)", "角膜スペキュラー色 (HDR)" },
            { "Cornea Spec Intensity", "角膜スペキュラー強度" },
            { "Could not find any Natane Toon Shaders!", "Natane Toon シェーダーが見つかりませんでした!" },
            { "Could not open the lilToon migration tool. Please check whether the migration assembly compiled successfully.", "lilToon 移行ツールを開けませんでした。移行用アセンブリが正しくコンパイルされているか確認してください。" },
            { "Create Backup", "バックアップを作成" },
            { "Create Duplicate in Hierarchy", "Hierarchy に複製を作成" },
            { "Create New Collection", "新しいコレクションを作成" },
            { "Create preset from this material", "このマテリアルからプリセットを作成" },
            { "Create Shader Variant Collection", "シェーダーバリアントコレクションを作成" },
            { "Culling Mode", "カリングモード" },
            { "Current Collection Info", "現在のコレクション情報" },
            { "Cutout", "カットアウト" },
            { "Dead Eye Texture", "死んだ目テクスチャ" },
            { "Dead State", "死んだ目状態" },
            { "Delete Runtime Prewarming Script", "ランタイム用プリウォームスクリプトを削除" },
            { "Delete Runtime Script", "ランタイムスクリプトを削除" },
            { "Delete", "削除" },
            { "Depth & Culling", "深度とカリング" },
            { "Destination Blend", "変換先ブレンド" },
            { "Detail Brightness", "ディテール明るさ" },
            { "Detail Highlights, Detail Shadows", "ディテールハイライト・ディテールシャドウ" },
            { "Detail", "ディテール" },
            { "Disable unused features and simplify the setup for Quest or VR targets.", "未使用機能を無効化し、Quest や VR 向けに構成を簡略化します。" },
            { "Disabling less important features will add headroom for mobile or VR.", "重要度の低い機能を無効化すると、モバイルや VR 向けの余裕が増えます。" },
            { "Dither Scale", "ディザースケール" },
            { "Dithering Scale", "ディザリングスケール" },
            { "Dithering Settings", "ディザリング設定" },
            { "Dithering Strength", "ディザリング強度" },
            { "Dot Density (0=None to 1=Full)", "ドット密度 (0=なし〜1=全面)" },
            { "Drag & drop a prefab or scene avatar here to scan for lilToon materials.", "Prefab またはシーン内アバターをここへドラッグ＆ドロップして lilToon マテリアルをスキャンします。" },
            { "Dual Eye Center", "両目中心" },
            { "Editor-Only Prewarming (VRChat Safe)", "Editor 限定プリウォーム (VRChat 安全)" },
            { "Effects", "エフェクト" },
            { "Enable Caustics", "コースティクスを有効化" },
            { "Enable Face SDF Rotation Tracking", "顔 SDF 回転追従を有効化" },
            { "Enable Hatching, Watercolor, Color Quantize, or other NPR features so the NPR slider has visible impact.", "ハッチング、水彩、Color Quantize などの NPR 機能を有効化すると、NPR スライダーの効果が見えやすくなります。" },
            { "Enable Inner Mesh Priority", "内側メッシュ優先度を有効化" },
            { "Enable Realistic Eye", "リアルな瞳を有効化" },
            { "Enable Ring Pulse", "リングパルスを有効化" },
            { "Enable Screen Tone", "スクリーントーンを有効化" },
            { "Enable Texture Polish", "テクスチャ研磨を有効化" },
            { "Enable Transparency", "透明を有効化" },
            { "Environment & Reflection", "環境と反射" },
            { "Error", "エラー" },
            { "Estimated Cost", "推定コスト" },
            { "Estimated Sampler Budget", "推定サンプラーバジェット" },
            { "Estimated Variants", "推定バリアント数" },
            { "Estimated Variants: material keyword sets (auto)", "推定バリアント数: マテリアルキーワード集合 (自動)" },
            { "Exact Compatibility (Preview)", "完全互換 (プレビュー)" },
            { "Exact Compatibility", "完全互換" },
            { "Excellent (A)", "優秀 (A)" },
            { "Export parameters to file", "パラメータをファイルへ出力" },
            { "Export to File", "ファイルへ出力" },
            { "Expression Color (HDR)", "表情色 (HDR)" },
            { "Expression Mode (Off/Spiral/Tearful/Shock)", "表情モード (Off/Spiral/Tearful/Shock)" },
            { "Expression Overlay", "表情オーバーレイ" },
            { "Expression Preset", "表情プリセット" },
            { "Extra Pass", "追加パス" },
            { "Eye Center 1 (UV)", "目の中心 1 (UV)" },
            { "Eye Center 2 (UV)", "目の中心 2 (UV)" },
            { "Eye Center Mode", "目の中心モード" },
            { "Eye Region Mask", "目領域マスク" },
            { "Eye Select Mode", "目選択モード" },
            { "Eye State (Normal/Star/Heart/Dead/Nervous)", "目状態 (通常/星/ハート/死んだ目/緊張)" },
            { "Eye State", "目状態" },
            { "Eye", "瞳" },
            { "Face Forward Direction", "顔の前方向" },
            { "Face Right Direction", "顔の右方向" },
            { "Fail Operation", "Fail 演算" },
            { "Failed to delete runtime script:", "ランタイムスクリプトの削除に失敗しました:" },
            { "Failed to generate runtime script:", "ランタイムスクリプトの生成に失敗しました:" },
            { "Failed to initialize material editor.", "マテリアルエディタの初期化に失敗しました。" },
            { "Failed", "失敗" },
            { "Fair (C)", "普通 (C)" },
            { "Falloff", "減衰" },
            { "Features", "機能" },
            { "Final Color Blending", "最終色ブレンド" },
            { "Finding ShaderVariantCollection...", "ShaderVariantCollection を検索中..." },
            { "Frequency Band", "周波数帯" },
            { "Fur", "ファー" },
            { "Generate Runtime Prewarming Script", "ランタイム用プリウォームスクリプトを生成" },
            { "Glare Color (HDR)", "グレア色 (HDR)" },
            { "Glitter, Shadow", "グリッター・影" },
            { "Global Opacity", "全体不透明度" },
            { "Glossiness", "光沢" },
            { "Good (B)", "良好 (B)" },
            { "GPU", "GPU" },
            { "Grade Scale", "グレードスケール" },
            { "Gradient Offset", "グラデーションオフセット" },
            { "Gradient Settings", "グラデーション設定" },
            { "Gradient Width", "グラデーション幅" },
            { "Heart Color (HDR)", "ハート色 (HDR)" },
            { "Heart State", "ハート状態" },
            { "Heart Texture", "ハートテクスチャ" },
            { "Heavy (D)", "重い (D)" },
            { "Help", "ヘルプ" },
            { "High", "高" },
            { "Highlight Blend (Prevent Blow-out)", "ハイライトブレンド (白飛び防止)" },
            { "Highlight Threshold", "ハイライトしきい値" },
            { "Highlights, Eye Shadow", "ハイライト・アイシャドウ" },
            { "Hue & Color", "色相と色" },
            { "Hue Animation Speed", "色相アニメーション速度" },
            { "Hue Offset", "色相オフセット" },
            { "Hybrid", "ハイブリッド" },
            { "In 'Replace Original' mode, the original material is modified in-place, so reference updates are unnecessary.", "`Replace Original` モードでは元のマテリアルをその場で更新するため、参照更新は不要です。" },
            { "Include Advanced Variants", "高度なバリアントを含める" },
            { "Include All Combinations (WARNING)", "全組み合わせを含める (警告)" },
            { "Include Basic Variants", "基本バリアントを含める" },
            { "Include Virtual Expression", "Virtual Expression を含める" },
            { "Inner Mesh Priority (BlendShape)", "内側メッシュ優先度 (BlendShape)" },
            { "Intensity", "強度" },
            { "Invert Mask", "マスクを反転" },
            { "Invert", "反転" },
            { "Iris Caustics", "虹彩コースティクス" },
            { "Iris Depth", "虹彩の奥行き" },
            { "Iris Focus", "虹彩フォーカス" },
            { "Iris highlight particle effect. Adds sparkling shine.", "虹彩のハイライト粒子エフェクトです。きらめく輝きを追加します。" },
            { "Iris Radius", "虹彩半径" },
            { "Iris Ring Pulse", "虹彩リングパルス" },
            { "Issue:", "問題:" },
            { "Last Duplicate:", "最後の複製:" },
            { "Last Duplicate", "最後の複製" },
            { "Left/Right Separation X Threshold", "左右分離 X しきい値" },
            { "Legacy (Auto)", "Legacy (自動)" },
            { "Light & Shadow", "ライトと影" },
            { "Light Size", "ライトサイズ" },
            { "Light Volume + LTCGI + Hatching is a high-risk sampler combination", "Light Volume + LTCGI + Hatching は高リスクなサンプラー構成です" },
            { "Light Volume + LTCGI + Hatching is a high-risk sampler combination. Be especially careful on D3D11.", "Light Volume + LTCGI + Hatching は高リスクなサンプラー構成です。特に D3D11 では注意してください。" },
            { "Light Volume + LTCGI + Screen Edge can hit the sampler limit quickly. Review the setup before layering more texture-heavy effects.", "Light Volume + LTCGI + Screen Edge はすぐにサンプラー上限へ達する可能性があります。さらに重いテクスチャ機能を重ねる前に構成を見直してください。" },
            { "Light Volume + LTCGI + Screen Edge is a high-risk sampler combination", "Light Volume + LTCGI + Screen Edge は高リスクなサンプラー構成です" },
            { "Light Volume is enabled, but the VRC Light Volumes package is not detected", "Light Volume が有効ですが、VRC Light Volumes パッケージが検出されません" },
            { "lilToon Match", "lilToon 近似" },
            { "lilToon Migration", "lilToon 移行" },
            { "Limbal Ring Color (HDR)", "輪部リング色 (HDR)" },
            { "Limbal Ring Intensity", "輪部リング強度" },
            { "Limbal Ring Width", "輪部リング幅" },
            { "Lines Color (HDR)", "ライン色 (HDR)" },
            { "Lines Offset", "ラインオフセット" },
            { "Lines Size", "ラインサイズ" },
            { "Lines Thickness", "ライン太さ" },
            { "Lit Softness", "明部の柔らかさ" },
            { "Lite: Disables some effects for optimization. Recommended for Quest.", "Lite: 最適化のため一部の効果を無効化します。Quest 向けに推奨です。" },
            { "Location", "場所" },
            { "Look Mixer", "ルックミキサー" },
            { "Look Mode", "ルックモード" },
            { "Low", "低" },
            { "LTCGI is enabled, but the LTCGI package is not detected", "LTCGI が有効ですが、LTCGI パッケージが検出されません" },
            { "Main Settings", "メイン設定" },
            { "Main Texture Animation", "メインテクスチャアニメーション" },
            { "Main Texture", "メインテクスチャ" },
            { "Mask Channel", "マスクチャンネル" },
            { "Mask Softness", "マスクのぼかし" },
            { "Mask Texture", "マスクテクスチャ" },
            { "Mask Threshold", "マスクしきい値" },
            { "Material Actions", "マテリアル操作" },
            { "Material Scan", "マテリアル走査" },
            { "Material Validator", "マテリアル検証" },
            { "Materials to Validate", "検証対象マテリアル" },
            { "Max Filter Radius", "最大フィルタ半径" },
            { "Matte Effect (Additional Gloss Reduction)", "マット効果 (追加光沢低減)" },
            { "Medium", "中" },
            { "Migration Mode", "移行モード" },
            { "Migration Version", "移行バージョン" },
            { "Min Filter Radius", "最小フィルタ半径" },
            { "Minimal Safe (Legacy)", "最小安全 (Legacy)" },
            { "Minimal Safe", "最小安全" },
            { "Minimum Brightness", "最小明るさ" },
            { "Mirror Right Eye UV", "右目 UV を反転" },
            { "Missing Shaders", "不足シェーダー" },
            { "Mode", "モード" },
            { "Moderate", "中程度" },
            { "Multi-Tone Shadow Settings", "多段影設定" },
            { "Natane Toon Eye Shader", "Natane Toon アイシェーダー" },
            { "Natane Eye Shader v1.1", "Natane アイシェーダー v1.1" },
            { "Natane Toon Shader Variant Collector", "Natane Toon Shader バリアント収集" },
            { "Natane Toon Shader Prewarming Settings", "Natane Toon Shader プリウォーム設定" },
            { "Natane", "Natane" },
            { "Near Limit", "上限間近" },
            { "Near PBR", "PBR 寄り" },
            { "Nervous State", "緊張状態" },
            { "Nervous Texture", "緊張テクスチャ" },
            { "No collection selected. Click 'Create New Collection' to create one.", "コレクションが選択されていません。`Create New Collection` を押して作成してください。" },
            { "No major contributors", "主な要因なし" },
            { "No materials selected. Use the buttons above to add materials.", "マテリアルが選択されていません。上のボタンから追加してください。" },
            { "No camera was found in the scene.\nSelect a camera object, or set the MainCamera tag and try again.", "シーン内にカメラが見つかりませんでした。\nカメラオブジェクトを選択するか、MainCamera タグを設定して再実行してください。" },
            { "No lilToon materials found in this prefab.", "この Prefab では lilToon マテリアルが見つかりませんでした。" },
            { "No", "いいえ" },
            { "Normal / Star / Heart / Dead / Nervous", "通常 / 星 / ハート / 死んだ目 / 緊張" },
            { "Normal State Texture", "通常状態テクスチャ" },
            { "Normal State", "通常状態" },
            { "Note: This system is VRChat-safe as it only runs in the Unity Editor, not at runtime.", "注記: この仕組みは Unity Editor 内でのみ動作し、ランタイムでは実行されないため VRChat でも安全です。" },
            { "NPR Weight is high, but no illustration-style NPR keywords are currently enabled.", "NPR Weight は高いですが、イラスト調の NPR キーワードが現在有効になっていません。" },
            { "NPR Weight", "NPR ウェイト" },
            { "NPR", "NPR" },
            { "Offset Factor", "オフセット係数" },
            { "Offset Units", "オフセット単位" },
            { "Open Console", "Console を開く" },
            { "Open Material Preset Browser", "マテリアルプリセットブラウザを開く" },
            { "Open Migration Tool", "移行ツールを開く" },
            { "Opaque", "不透明" },
            { "Optional", "任意" },
            { "Options", "オプション" },
            { "Over Limit", "上限超過" },
            { "Overall Brightness", "全体の明るさ" },
            { "Parallax Intensity", "視差強度" },
            { "Parallax", "視差" },
            { "Parity Details", "互換差分詳細" },
            { "Parity Warnings", "互換警告" },
            { "Pass Operation", "Pass 演算" },
            { "Paste parameters from clipboard", "クリップボードからパラメータを貼り付け" },
            { "Paste", "貼り付け" },
            { "Pattern Size (Dot Size)", "パターンサイズ (ドットサイズ)" },
            { "PBR Weight is high, but smoothness / metallic / reflection are still very weak.", "PBR Weight は高いですが、Smoothness / Metallic / Reflection がまだ弱いです。" },
            { "PBR Weight", "PBR ウェイト" },
            { "PBR", "PBR" },
            { "PCSS Settings", "PCSS 設定" },
            { "Performance Rating Check", "パフォーマンス評価チェック" },
            { "Performance Rating", "パフォーマンス評価" },
            { "Performance Tier (Quality/Balanced/Lite)", "パフォーマンス階層 (Quality/Balanced/Lite)" },
            { "Performance", "パフォーマンス" },
            { "Please create or select a collection first!", "先にコレクションを作成または選択してください!" },
            { "Prewarm on Build", "ビルド時にプリウォーム" },
            { "Prewarm Shaders Now", "今すぐシェーダーをプリウォーム" },
            { "Preset Browser", "プリセットブラウザ" },
            { "Prefab Selection", "Prefab 選択" },
            { "Prefab Settings", "Prefab 設定" },
            { "Priority Mask", "優先度マスク" },
            { "Priority Mode", "優先度モード" },
            { "Project-wide material scan is manual so opening the tool stays responsive on large projects.", "大規模プロジェクトでもツールの応答性を保つため、プロジェクト全体スキャンは手動実行です。" },
            { "Project", "プロジェクト" },
            { "Pulse Amount", "パルス量" },
            { "Pulse Power", "パルス強さ" },
            { "Pulse Speed", "パルス速度" },
            { "Pure Toon", "純トゥーン" },
            { "Pupil Aspect XY (1,1=Circle)", "瞳孔アスペクト XY (1,1=円)" },
            { "Pupil Color (HDR)", "瞳孔色 (HDR)" },
            { "Pupil Size", "瞳孔サイズ" },
            { "Raise either Toon or PBR a bit so the material keeps a clear base response.", "Toon または PBR を少し上げて、マテリアルのベース反応を明確にしてください。" },
            { "Ramp Texture Settings", "ランプテクスチャ設定" },
            { "Ramp Texture", "ランプテクスチャ" },
            { "Random Seed", "ランダムシード" },
            { "Rating", "評価" },
            { "Read Mask", "読込マスク" },
            { "Realistic Eye", "リアルな瞳" },
            { "Reapply lilToon Match", "lilToon 近似を再適用" },
            { "Reference Value", "参照値" },
            { "Rendering Settings", "描画設定" },
            { "Rendering Type", "描画タイプ" },
            { "Replace Original (Destructive)", "元を置換 (破壊的)" },
            { "Rescan Materials", "マテリアルを再スキャン" },
            { "Review Hatching or third-party lighting before adding more heavy texture features.", "さらに重いテクスチャ機能を追加する前に、Hatching やサードパーティライティングを見直してください。" },
            { "Review Smoothness, Metallic, and Reflection so the PBR-heavy look reads more clearly.", "PBR 寄りの見た目が分かりやすくなるよう、Smoothness、Metallic、Reflection を見直してください。" },
            { "Ring Color (HDR)", "リング色 (HDR)" },
            { "Ring Count", "リング数" },
            { "Ring Radius", "リング半径" },
            { "Ring Width", "リング幅" },
            { "Rock Angle", "揺れ角度" },
            { "Rock Sharpness", "揺れの鋭さ" },
            { "Rock Speed", "揺れ速度" },
            { "Run Tools > Natane > VRChat > LTCGI Re-detect, or disable LTCGI if you do not need it.", "`Tools > Natane > VRChat > LTCGI Re-detect` を実行するか、不要なら LTCGI を無効化してください。" },
            { "Run Tools > Natane > VRChat > VRC Light Volumes Re-detect, or disable Light Volume if you do not need it.", "`Tools > Natane > VRChat > VRC Light Volumes Re-detect` を実行するか、不要なら Light Volume を無効化してください。" },
            { "Runtime Prewarming (Non-VRChat Only)", "ランタイムプリウォーム (非 VRChat 専用)" },
            { "Runtime prewarming script has been deleted successfully.", "ランタイム用プリウォームスクリプトを削除しました。" },
            { "Runtime prewarming script has been generated successfully!", "ランタイム用プリウォームスクリプトを生成しました!" },
            { "Runtime prewarming script is DISABLED", "ランタイム用プリウォームスクリプトは無効です" },
            { "Runtime prewarming script is ENABLED", "ランタイム用プリウォームスクリプトは有効です" },
            { "Sampler", "サンプラー" },
            { "Sample Quality", "サンプル品質" },
            { "Saturation", "彩度" },
            { "Save as Preset", "プリセットとして保存" },
            { "Save Collection", "コレクションを保存" },
            { "Scan for lilToon Materials", "lilToon マテリアルをスキャン" },
            { "Scale", "スケール" },
            { "Screen Edge Split", "Screen Edge 分割" },
            { "Screen FX Overlay Created", "Screen FX オーバーレイを作成" },
            { "Screen Tone (Halftone Overlay)", "スクリーントーン (ハーフトーンオーバーレイ)" },
            { "Sclera Shadow Strength", "強膜影強度" },
            { "Sclera Tint (HDR)", "強膜色味 (HDR)" },
            { "Search:", "検索:" },
            { "Select", "選択" },
            { "Safe", "安全" },
            { "SDF Intensity", "SDF 強度" },
            { "SDF Map", "SDF マップ" },
            { "SDF Offset", "SDF オフセット" },
            { "SDF Shadow Map Settings", "SDF シャドウマップ設定" },
            { "SDF Softness", "SDF の柔らかさ" },
            { "Shader Count", "シェーダー数" },
            { "Shader Not Found", "シェーダーが見つかりません" },
            { "Shader Prewarming Complete", "シェーダープリウォーム完了" },
            { "Shader Prewarming", "シェーダープリウォーム" },
            { "Shader Prewarming Settings", "シェーダープリウォーム設定" },
            { "Shader Type", "シェーダータイプ" },
            { "Shader Variant Collection created successfully!", "シェーダーバリアントコレクションを作成しました!" },
            { "Shader Variant Collector", "シェーダーバリアント収集" },
            { "Shadow Blend (Prevent Crush)", "影ブレンド (黒つぶれ防止)" },
            { "Shadow Blend", "影ブレンド" },
            { "Shadow Blur", "影ぼかし" },
            { "Shadow Border", "影境界" },
            { "Shadow Color (1st)", "影色 (1段目)" },
            { "Shadow Color (2nd)", "影色 (2段目)" },
            { "Shadow Color (3rd)", "影色 (3段目)" },
            { "Shadow Color Texture Settings", "影色テクスチャ設定" },
            { "Shadow Color", "影色" },
            { "Shadow Env Strength", "影環境色強度" },
            { "Shadow Hue Shift", "影色相シフト" },
            { "Shadow Offset", "影オフセット" },
            { "Shadow Push", "影押し出し" },
            { "Shadow Receive Mask Settings", "影受けマスク設定" },
            { "Shadow Receive Mask", "影受けマスク" },
            { "Shadow Saturation", "影彩度" },
            { "Shadow Sharpness", "影の鋭さ" },
            { "Shadow Steps", "影段数" },
            { "Shadow Strength", "影強度" },
            { "Shadow Threshold", "影しきい値" },
            { "Shading Grade Map Settings", "シェーディンググレードマップ設定" },
            { "Shading Mode", "シェーディングモード" },
            { "Shock Ring Settings", "ショックリング設定" },
            { "Show Preview After Conversion", "変換後にプレビューを表示" },
            { "Soft NPR", "ソフト NPR" },
            { "Softness", "柔らかさ" },
            { "Source Blend", "変換元ブレンド" },
            { "Source Shader", "元シェーダー" },
            { "Speed", "速度" },
            { "Spiral Line Width", "スパイラル線幅" },
            { "Spiral Settings", "スパイラル設定" },
            { "Spiral Tightness", "スパイラル密度" },
            { "StandardToon (lilToon)", "lilToon互換ベース" },
            { "StandardToon Mode", "lilToon互換ベース" },
            { "StandardToon Settings", "lilToon互換ベース設定" },
            { "Starter Presets", "スタータープリセット" },
            { "Star Color (HDR)", "星色 (HDR)" },
            { "Star State", "星状態" },
            { "Star Texture", "星テクスチャ" },
            { "Status", "状態" },
            { "Stencil", "ステンシル" },
            { "Step Border Smoothing", "段境界の平滑化" },
            { "Strength", "強さ" },
            { "Suggestion:", "提案:" },
            { "Success", "成功" },
            { "Script Deleted", "スクリプト削除完了" },
            { "Script Generated", "スクリプト生成完了" },
            { "Syncs with music when AudioLink is installed in the VRChat world.", "VRChat ワールドに AudioLink が導入されている場合、音楽と同期します。" },
            { "Symmetry Pivot X", "対称軸ピボット X" },
            { "Target Prefab", "対象 Prefab" },
            { "Tear Flow", "涙の流れ" },
            { "Tear Rim Highlight", "涙縁ハイライト" },
            { "Tear Settings", "涙設定" },
            { "Texture & Color", "テクスチャと色" },
            { "Texture Blend", "テクスチャブレンド" },
            { "Texture Color Preservation", "テクスチャ色保持" },
            { "Texture Compression Check", "テクスチャ圧縮チェック" },
            { "Texture Polish", "テクスチャ研磨" },
            { "Texture Size Check", "テクスチャサイズチェック" },
            { "This material uses the Screen Edge split variant. Sampler pressure is lower, but the extra pass adds one draw call.", "このマテリアルは Screen Edge 分割バリアントを使用しています。サンプラー負荷は低めですが、追加パスにより Draw Call が 1 つ増えます。" },
            { "Using Light Volume and LTCGI together can quickly approach the sampler limit. Be careful when combining them with other heavy features.", "Light Volume と LTCGI を同時に使うとサンプラー上限へすぐ近づきます。ほかの重い機能と組み合わせる際は注意してください。" },
            { "This will remove", "次を削除します" },
            { "Threshold", "しきい値" },
            { "Thickness", "厚み" },
            { "Tint Color (HDR)", "色味 (HDR)" },
            { "Tone Color", "トーン色" },
            { "Toon Shading", "トゥーンシェーディング" },
            { "Toon Weight", "トゥーンウェイト" },
            { "Toon-PBR Hybrid", "トゥーン-PBR ハイブリッド" },
            { "Toon", "トゥーン" },
            { "Top Color", "上側の色" },
            { "Top Contributors", "主な要因" },
            { "Transparency Dither Scale", "透明ディザースケール" },
            { "Transparency Resolve Mode", "透明解決モード" },
            { "Transparent", "透明" },
            { "Twist", "ねじれ" },
            { "Unknown", "不明" },
            { "Unused Features Check", "未使用機能チェック" },
            { "Use Ambient Occlusion (AO)", "アンビエントオクルージョン (AO) を使用" },
            { "Use Dithering (Halftone)", "ディザリング (ハーフトーン) を使用" },
            { "Use Multi-Tone Shadow", "多段影を使用" },
            { "Use PCSS Soft Shadows", "PCSS ソフトシャドウを使用" },
            { "Use Ramp Texture", "ランプテクスチャを使用" },
            { "Use Region Mask", "領域マスクを使用" },
            { "Use SDF Shadow Map", "SDF シャドウマップを使用" },
            { "Use Shading Grade Map", "シェーディンググレードマップを使用" },
            { "Use Shadow Color Texture", "影色テクスチャを使用" },
            { "Use Shadow Receive Mask", "影受けマスクを使用" },
            { "Use Texture", "テクスチャを使用" },
            { "Use when the face and eyes share the same material. Specify the eye region with a mask.", "顔と目が同じマテリアルを共有している場合に使います。マスクで目の領域を指定してください。" },
            { "Usage: Add the RuntimeShaderPrewarming component to a GameObject in your scene and assign the ShaderVariantCollection.", "使い方: シーン内の GameObject に RuntimeShaderPrewarming コンポーネントを追加し、ShaderVariantCollection を割り当ててください。" },
            { "Usage: Add this component to a GameObject in your scene and assign the ShaderVariantCollection.", "使い方: このコンポーネントをシーン内の GameObject に追加し、ShaderVariantCollection を割り当ててください。" },
            { "Validate All", "すべて検証" },
            { "Validates materials for VRChat optimization, performance issues, and common problems.\nAuto-fix suggestions provided where possible.", "VRChat 向け最適化、パフォーマンス問題、よくある問題を検証します。\n可能な場合は自動修正候補も表示します。" },
            { "Validation Results", "検証結果" },
            { "Validation Settings", "検証設定" },
            { "Variant Collection", "バリアントコレクション" },
            { "Variant Count", "バリアント数" },
            { "Variant Options", "バリアント設定" },
            { "VCC Listing", "VCC リスト" },
            { "Vertex Color Shadow Threshold", "頂点カラー影しきい値" },
            { "Vignette Effect", "ビネット効果" },
            { "Virtual expression: Dissolve, Hue Shift, Emission Animations", "Virtual Expression: Dissolve、Hue Shift、Emission アニメーション" },
            { "Visual Match (Approximate)", "見た目優先 (近似)" },
            { "Visual Match", "見た目優先" },
            { "VRChat Optimization Check", "VRChat 最適化チェック" },
            { "Warnings Detected", "警告を検出" },
            { "Wirelight", "Wirelight" },
            { "Wrap Amount", "ラップ量" },
            { "Write Mask", "書込マスク" },
            { "Wobble Speed", "揺れ速度" },
            { "Wobble Strength", "揺れ強度" },
            { "Yes", "はい" },
            { "Z Fail Operation", "Z Fail 演算" },
            { "Z Test", "Z テスト" },
            { "   i Multiple shadow layers detected (converted as multi-shadow)", "   i 複数の影レイヤーを検出 (多段影として変換)" },
            { "Z Write", "Z 書き込み" },
            { "Anime-style cel shading with clean and controllable shadow transitions.", "クリーンでコントロールしやすい影遷移を持つアニメ調セルシェーディングです。" },
            { "AO and dithering settings have been moved to the Light & Shadow tab.", "AO とディザリングの設定は Light & Shadow タブへ移動しました。" },
            { "To soften shadows, start with Shadow Blend around 0.3 to 0.5, then adjust Lit Softness if needed.", "影を柔らかくしたい場合は、まず Shadow Blend を 0.3〜0.5 前後にし、必要に応じて Lit Softness を調整してください。" },
            { "The ramp texture should run from dark on the left to bright on the right.", "ランプテクスチャは左が暗く、右が明るくなるように設定してください。" },
            { "Toon gives stepped cel shading. Gradient gives softer transitions. StandardToon is used for lilToon-compatible migrated materials.", "Toon は段階的なセルシェーディングです。Gradient はより柔らかい遷移になります。互換ベースは lilToon 由来の素材で使われます。" },
            { "This material appears to be using the lilToon-compatible StandardToon mode.", "このマテリアルは lilToon 互換ベースを使用しているようです。" },
            { "Adjust shadow hue and saturation in HSV space.", "HSV 空間で影の色相と彩度を調整します。" },
            { "Positive values brighten the shadow boundary. Negative values deepen it.", "正の値は影境界を明るくし、負の値はより深くします。" },
            { "Controls how much light wraps around the form.", "光が形状へどの程度回り込むかを制御します。" },
            { "Softens transitions on lit areas.", "明部側の遷移を柔らかくします。" },
            { "Higher values soften and widen the shadow transition.", "値を上げると影の遷移が柔らかく広がります。" },
            { "Shadow Blend is set high. Check other softness values if the result feels too soft.", "Shadow Blend が高めです。結果が柔らかすぎる場合は他の Softness 値も確認してください。" },
            { "Uses vertex color R to offset the shadow threshold per area.", "頂点カラー R を使って領域ごとに影しきい値をオフセットします。" },
            { "Controls how soft the light-to-shadow transition is.", "明部から影への遷移の柔らかさを制御します。" },
            { "StandardToon is the lilToon-compatible shading path used by migrated materials.", "lilToon互換ベースは移行マテリアルで使われる互換シェーディング経路です。" },
            { "Sets where the second shadow tone begins.", "2段目の影色が始まる位置を設定します。" },
            { "Sets where the deepest shadow tone begins.", "最も深い影色が始まる位置を設定します。" },
            { "Use descending border values: 1st > 2nd > 3rd.", "境界値は 1段目 > 2段目 > 3段目 の降順で設定してください。" },
            { "Recommended values are usually 2 to 3 steps.", "推奨値は通常 2〜3 段です。" },
            { "Lower values sharpen the border. Higher values soften it.", "値を下げると境界が鋭くなり、上げると柔らかくなります。" },
            { "Smooths the borders between multi-tone shadow steps.", "多段影の段境界を滑らかにします。" },
            { "White areas receive less shadow. Black areas receive full shadow.", "白い領域は影が弱く、黒い領域は完全な影を受けます。" },
            { "Darkens creases and recessed areas using an AO map.", "AO マップを使って溝や凹部を暗くします。" },
            { "Adds a halftone-like pattern to shadow transitions.", "影の遷移にハーフトーン風パターンを追加します。" },
            { "Controls shadow placement using an SDF texture.", "SDF テクスチャを使って影の配置を制御します。" },
            { "Lets face SDF shadows rotate with light direction.", "顔 SDF の影が光方向に合わせて回転するようにします。" },
            { "Adjusts shadow strength locally using a texture map.", "テクスチャマップで局所的に影の強さを調整します。" },
            { "PCSS adds softer, distance-aware shadows for directional lights.", "PCSS は距離に応じた柔らかい影をディレクショナルライトに追加します。" },
            { "Partial UV (top-right/top-left etc.): Set Eye Select Mode to 'Nearest Center'.\nSymmetrical UV: Set Eye Center Mode to 'Symmetry From Center1' and adjust Symmetry Pivot X.", "Partial UV (右上 / 左上など): Eye Select Mode を `Nearest Center` に設定してください。\n左右対称 UV: Eye Center Mode を `Symmetry From Center1` にし、Symmetry Pivot X を調整してください。" },
            { "Nearest Center: Selects the center closest to the UV coordinate.\nSymmetry From Center1: Symmetrizes based on Center1.", "Nearest Center: UV 座標に最も近い中心を選択します。\nSymmetry From Center1: Center1 を基準に左右対称化します。" },
            { "Uses a texture to control shadow colors. Apply Strength controls how strongly the texture affects the result.", "テクスチャを使って影色を制御します。Apply Strength で結果への影響度を調整します。" },
            { "Migrated materials opt into a dedicated exact-compatibility flag and use a parity-focused StandardToon path.\nSome features such as MatCap still require manual review, so check warnings after conversion.", "移行後のマテリアルは専用の完全互換フラグを有効にし、見た目を寄せるための互換ベースを使用します。\nMatCap など一部の機能は手動確認が必要なため、変換後に警告を確認してください。" },
            { "All active lilToon features (rim light, outline, emission, MatCap, specular, etc.) will be converted and enabled.\nThis is a Natane-native approximation path and does not guarantee pixel-perfect parity.", "有効な lilToon 機能 (リムライト、アウトライン、発光、MatCap、スペキュラーなど) をすべて変換して有効化します。\nこれは Natane ネイティブの近似経路であり、ピクセル単位の完全一致は保証しません。" },
            { "Only basic settings (texture, color, shadow) are enabled. Other features are migrated in OFF state.\nProperty values are preserved, so you can enable features individually after migration.", "基本設定 (テクスチャ、色、影) のみを有効にし、その他の機能は OFF のまま移行します。\nプロパティ値は保持されるため、移行後に必要な機能だけ個別に有効化できます。" },
            { "WARNING: This will permanently modify your original materials!\nMake sure you have a backup of your project.", "警告: 元のマテリアルを恒久的に変更します。\n必ずプロジェクトのバックアップを取ってください。" },
            { "Creates a duplicate in the hierarchy with converted materials, keeping the original prefab untouched.\nAuto-update References can repoint the original prefab to the new materials if needed.", "Hierarchy に変換済みマテリアルを使う複製を作成し、元の Prefab はそのまま残します。\n必要なら Auto-update References で元の Prefab の参照先を新しいマテリアルへ向け直せます。" },
            { "Shader prewarming compiles shader variants in advance to prevent stuttering during gameplay.\nThis is especially important for VRChat worlds and avatars.", "シェーダープリウォームはシェーダーバリアントを事前コンパイルし、プレイ中のカクつきを防ぎます。\nこれは VRChat のワールドやアバターで特に重要です。" },
            { "WARNING: Runtime prewarming scripts DO NOT work in VRChat!\nOnly enable this for non-VRChat projects where you need runtime shader prewarming.", "警告: ランタイムプリウォームスクリプトは VRChat では動作しません。\nランタイムシェーダープリウォームが必要な非 VRChat プロジェクトでのみ有効にしてください。" },
            { "Features:\n遯ｶ・｢ Browse and apply material presets visually\n遯ｶ・｢ Filter by category and search by name\n遯ｶ・｢ Create presets from existing materials\n遯ｶ・｢ Share parameters via file or clipboard\n遯ｶ・｢ Generate VTuber-optimized presets\n\nUsage:\n1. Select a target material\n2. Browse presets and click Apply\n3. Create presets from materials\n4. Share with Export/Import", "機能:\n・マテリアルプリセットを視覚的に参照して適用\n・カテゴリで絞り込み、名前で検索\n・既存マテリアルからプリセットを作成\n・ファイルまたはクリップボードでパラメータ共有\n・VTuber 向け最適化プリセットを生成\n\n使い方:\n1. 対象マテリアルを選択\n2. プリセットを見て Apply を押す\n3. マテリアルからプリセットを作成\n4. Export / Import で共有" },
            { "Generate high-quality VTuber material presets.\n\nThe following 5 presets will be created:\n1. Character Skin - Soft cell shading with SSS\n2. Character Hair - Glossy anime-style hair\n3. Character Clothing - Clean anime style\n4. Character Eyes - Sparkling eyes\n5. Live Performance - Lightweight & high performance\n\nLocation: Assets/NataneToon/Runtime/Presets/VTuber/\n\nGenerate?", "高品質な VTuber 向けマテリアルプリセットを生成します。\n\n次の 5 種類のプリセットを作成します:\n1. Character Skin - SSS 付きの柔らかいセルシェーディング\n2. Character Hair - 光沢感のあるアニメ調ヘア\n3. Character Clothing - クリーンなアニメ調衣装\n4. Character Eyes - きらめく瞳\n5. Live Performance - 軽量で高パフォーマンス\n\n保存先: Assets/NataneToon/Runtime/Presets/VTuber/\n\n生成しますか?" },
            { "Generate", "生成" },
            { "Complete", "完了" },
            { "Preset Applied", "プリセット適用完了" },
            { "Material Preset Browser - Help", "マテリアルプリセットブラウザ - ヘルプ" },
            { "Generate VTuber Presets", "VTuber プリセット生成" },
            { "Create Preset from Material", "マテリアルからプリセット作成" },
            { "Choose where to save the preset", "プリセットの保存先を選択してください" },
            { "Preset Created", "プリセット作成完了" },
            { "Export Material Parameters", "マテリアルパラメータを書き出し" },
            { "Export Successful", "書き出し完了" },
            { "Import Material Parameters", "マテリアルパラメータを読み込み" },
            { "Import Successful", "読み込み完了" },
            { "Copied to Clipboard", "クリップボードへコピー" }
        };

        private static readonly TranslationPattern[] JapaneseFallbackPatterns =
        {
            new TranslationPattern(@"^(?<layer>.+) Tex Mask$", m => $"{m.Groups["layer"].Value} テクスマスク"),
            new TranslationPattern(@"^(?<layer>.+) Texture Settings$", m => $"{m.Groups["layer"].Value} テクスチャ設定"),
            new TranslationPattern(@"^Enable (?<layer>.+) Texture$", m => $"{m.Groups["layer"].Value} テクスチャを有効化"),
            new TranslationPattern(@"^An error occurred while drawing the inspector: (?<message>.+)$", m => $"インスペクタ描画中にエラーが発生しました: {m.Groups["message"].Value}"),
            new TranslationPattern(@"^Error drawing (?<section>.+) section: (?<message>.+)$", m => $"{m.Groups["section"].Value} セクションの描画エラー: {m.Groups["message"].Value}"),
            new TranslationPattern(@"^Selected: (?<count>.+) materials$", m => $"選択中: {m.Groups["count"].Value} 個のマテリアル"),
            new TranslationPattern(@"^Selected Materials \((?<count>.+)\):$", m => $"選択中のマテリアル ({m.Groups["count"].Value}):"),
            new TranslationPattern(@"^Example: (?<from>.+) -> (?<to>.+)$", m => $"例: {m.Groups["from"].Value} -> {m.Groups["to"].Value}"),
            new TranslationPattern(@"^Materials with (?<property>.+): (?<count>.+)/(?<total>.+)$", m => $"{m.Groups["property"].Value} を持つマテリアル: {m.Groups["count"].Value}/{m.Groups["total"].Value}"),
            new TranslationPattern(@"^(?<count>.+) presets found$", m => $"{m.Groups["count"].Value} 件のプリセットを検出"),
            new TranslationPattern(@"^Convert All to (?<variant>.+)$", m => $"すべてを {m.Groups["variant"].Value} に変換"),
            new TranslationPattern(@"^Adjusted (?<param>.+) in (?<count>.+) materials$", m => $"{m.Groups["count"].Value} 個のマテリアルで {m.Groups["param"].Value} を調整しました"),
            new TranslationPattern(@"^Set (?<param>.+) in (?<count>.+) materials$", m => $"{m.Groups["count"].Value} 個のマテリアルで {m.Groups["param"].Value} を設定しました"),
            new TranslationPattern(@"^(?<action>Enabled|Disabled) (?<featureCount>.+) features in (?<count>.+) materials$", m => $"{m.Groups["count"].Value} 個のマテリアルで {m.Groups["featureCount"].Value} 個の機能を{(m.Groups["action"].Value == "Enabled" ? "有効化" : "無効化")}しました"),
            new TranslationPattern(@"^Replaced (?<property>.+) in (?<count>.+) materials$", m => $"{m.Groups["count"].Value} 個のマテリアルで {m.Groups["property"].Value} を置換しました"),
            new TranslationPattern(@"^Disabled all features in (?<count>.+) materials$", m => $"{m.Groups["count"].Value} 個のマテリアルですべての機能を無効化しました"),
            new TranslationPattern(@"^Shader not found: (?<name>.+)$", m => $"シェーダーが見つかりません: {m.Groups["name"].Value}"),
            new TranslationPattern(@"^Converted (?<count>.+) materials to (?<variant>.+) variant$", m => $"{m.Groups["count"].Value} 個のマテリアルを {m.Groups["variant"].Value} バリアントへ変換しました"),
            new TranslationPattern(@"^Collected (?<count>.+) shader variants!$", m => $"{m.Groups["count"].Value} 個のシェーダーバリアントを収集しました!"),
            new TranslationPattern(@"^Scanning materials\.\.\. \((?<progress>.+)\)$", m => $"マテリアルを走査中... ({m.Groups["progress"].Value})"),
            new TranslationPattern(@"^Warming up collection \((?<count>.+) variants\)\.\.\.$", m => $"コレクションをプリウォーム中 ({m.Groups["count"].Value} バリアント)..."),
            new TranslationPattern(@"^Conversion Complete: Successfully converted (?<success>.+)/(?<total>.+) materials\.$", m => $"変換完了: {m.Groups["total"].Value} 個中 {m.Groups["success"].Value} 個のマテリアルを正常に変換しました。"),
            new TranslationPattern(@"^Error: (?<message>.+)$", m => $"エラー: {m.Groups["message"].Value}"),
            new TranslationPattern(@"^Are you sure you want to convert (?<count>.+) materials\?$", m => $"{m.Groups["count"].Value} 個のマテリアルを変換しますか？"),
            new TranslationPattern(@"^Are you sure you want to convert (?<count>.+) materials in '(?<name>.+)'\?$", m => $"'{m.Groups["name"].Value}' 内の {m.Groups["count"].Value} 個のマテリアルを変換しますか？"),
            new TranslationPattern(@"^Converting (?<progress>.+): (?<name>.+)$", m => $"変換中 {m.Groups["progress"].Value}: {m.Groups["name"].Value}"),
            new TranslationPattern(@"^Found (?<count>.+) lilToon Materials$", m => $"lilToon マテリアルを {m.Groups["count"].Value} 件検出"),
            new TranslationPattern(@"^Target: (?<count>.+) materials$", m => $"対象: {m.Groups["count"].Value} 個のマテリアル"),
            new TranslationPattern(@"^Used by: (?<path>.+) \[Slot (?<slot>.+)\]$", m => $"使用箇所: {m.Groups["path"].Value} [Slot {m.Groups["slot"].Value}]"),
            new TranslationPattern(@"^Paste parameters from:\n\nMaterial: (?<material>.+)\nExported by: (?<exportedBy>.+)\nExport date: (?<exportDate>.+)\nNotes: (?<notes>[\s\S]*)\n\nThis will overwrite current settings of '(?<target>.+)'$", m => $"次の内容からパラメータを貼り付けます:\n\nマテリアル: {m.Groups["material"].Value}\n出力者: {m.Groups["exportedBy"].Value}\n出力日: {m.Groups["exportDate"].Value}\nメモ: {m.Groups["notes"].Value}\n\n'{m.Groups["target"].Value}' の現在設定を上書きします"),
            new TranslationPattern(@"^   > Outline Width Adjusted: (?<from>.+) -> (?<to>.+)$", m => $"   > アウトライン幅を調整: {m.Groups["from"].Value} -> {m.Groups["to"].Value}"),
            new TranslationPattern(@"^(?<count>.+) warnings detected\.\nCheck the console log for details\.\n\nOpen Console\?$", m => $"{m.Groups["count"].Value} 件の警告を検出しました。\n詳細は Console ログを確認してください。\n\nConsole を開きますか？"),
            new TranslationPattern(@"^Create a duplicate of '(?<name>.+)' and convert (?<count>.+) materials\?\nThe original prefab will not be modified\.$", m => $"'{m.Groups["name"].Value}' の複製を作成して {m.Groups["count"].Value} 個のマテリアルを変換しますか？\n元の Prefab は変更されません。"),
            new TranslationPattern(@"^Created duplicate '(?<duplicate>.+)' of '(?<source>.+)' in hierarchy \((?<count>.+) material slots replaced\)\.$", m => $"Hierarchy に '{m.Groups["source"].Value}' の複製 '{m.Groups["duplicate"].Value}' を作成しました ({m.Groups["count"].Value} 個のマテリアルスロットを置換)。"),
            new TranslationPattern(@"^Convert Selected \((?<count>.+)\)$", m => $"選択を変換 ({m.Groups["count"].Value})"),
            new TranslationPattern(@"^Duplicate & Convert \((?<count>.+)\)$", m => $"複製して変換 ({m.Groups["count"].Value})"),
            new TranslationPattern(@"^Success: (?<count>.+)$", m => $"成功: {m.Groups["count"].Value}"),
            new TranslationPattern(@"^Failed: (?<count>.+)$", m => $"失敗: {m.Groups["count"].Value}"),
            new TranslationPattern(@"^Warnings: (?<count>.+)$", m => $"警告: {m.Groups["count"].Value}"),
            new TranslationPattern(@"^Errors: (?<count>.+)$", m => $"エラー: {m.Groups["count"].Value}"),
            new TranslationPattern(@"^Info: (?<count>.+)$", m => $"情報: {m.Groups["count"].Value}"),
            new TranslationPattern(@"^(?<features>\d+) features are enabled\. GPU cost is heavy \(Rating: D\)$", m => $"{m.Groups["features"].Value} 個の機能が有効です。GPU コストは重いです (評価: D)"),
            new TranslationPattern(@"^(?<features>\d+) features are enabled\. GPU cost is moderate \(Rating: C\)$", m => $"{m.Groups["features"].Value} 個の機能が有効です。GPU コストは中程度です (評価: C)"),
            new TranslationPattern(@"^Check sampler headroom before enabling more heavy features\. Main contributors: (?<summary>.+)$", m => $"さらに重い機能を有効にする前に、サンプラーの余裕を確認してください。主な要因: {m.Groups["summary"].Value}"),
            new TranslationPattern(@"^Check the current setup before enabling Light Volume or LTCGI\. Main contributors: (?<summary>.+)$", m => $"Light Volume や LTCGI を有効にする前に現在の構成を確認してください。主な要因: {m.Groups["summary"].Value}"),
            new TranslationPattern(@"^Disable heavy features to get back under the limit\. Main contributors: (?<summary>.+)$", m => $"重い機能を無効化して上限未満へ戻してください。主な要因: {m.Groups["summary"].Value}"),
            new TranslationPattern(@"^Estimated sampler usage exceeds the limit \((?<usage>.+)\)$", m => $"推定サンプラー使用数が上限を超えています ({m.Groups["usage"].Value})"),
            new TranslationPattern(@"^Estimated sampler usage is in the caution range \((?<usage>.+)\)$", m => $"推定サンプラー使用数が注意域に入っています ({m.Groups["usage"].Value})"),
            new TranslationPattern(@"^Estimated sampler usage is near the limit \((?<usage>.+)\)$", m => $"推定サンプラー使用数が上限間近です ({m.Groups["usage"].Value})"),
            new TranslationPattern(@"^Estimated sampler usage is close to the limit \((?<usage>.+)\)\. Review the current setup before enabling more heavy features\.$", m => $"推定サンプラー使用数が上限間近です ({m.Groups["usage"].Value})。さらに重い機能を有効にする前に現在の構成を見直してください。"),
            new TranslationPattern(@"^Estimated sampler usage is in the caution range \((?<usage>.+)\)\. Be careful when adding features such as Light Volume or LTCGI\.$", m => $"推定サンプラー使用数が注意域に入っています ({m.Groups["usage"].Value})。Light Volume や LTCGI などを追加する際は注意してください。"),
            new TranslationPattern(@"^Estimated sampler usage is over the limit \((?<usage>.+)\)\. The current look is preserved, but new heavy features cannot be enabled\.$", m => $"推定サンプラー使用数が上限を超えています ({m.Groups["usage"].Value})。現在の見た目は維持されますが、新たな重い機能は有効にできません。"),
            new TranslationPattern(@"^Fixed (?<count>.+) issues automatically\.\nRemaining issues require manual intervention\.$", m => $"{m.Groups["count"].Value} 件の問題を自動修正しました。\n残りは手動対応が必要です。"),
            new TranslationPattern(@"^Fixed issue for material: (?<name>.+)$", m => $"マテリアルの問題を修正: {m.Groups["name"].Value}"),
            new TranslationPattern(@"^Light Volume and LTCGI are enabled together \(estimated (?<usage>.+)\)$", m => $"Light Volume と LTCGI が同時に有効です (推定 {m.Groups["usage"].Value})"),
            new TranslationPattern(@"^Review Screen Edge or third-party lighting\. Main contributors: (?<summary>.+)$", m => $"Screen Edge やサードパーティライティングを見直してください。主な要因: {m.Groups["summary"].Value}"),
            new TranslationPattern(@"^Review the current setup before enabling more heavy features\. Main contributors: (?<summary>.+)$", m => $"さらに重い機能を有効にする前に現在の構成を見直してください。主な要因: {m.Groups["summary"].Value}"),
            new TranslationPattern(@"^Successfully applied preset '(?<preset>.+)' to material '(?<material>.+)'\nInspector UI has been updated to show active features\.$", m => $"プリセット '{m.Groups["preset"].Value}' をマテリアル '{m.Groups["material"].Value}' へ正常に適用しました。\nインスペクタ UI は有効機能が分かる状態へ更新されています。"),
            new TranslationPattern(@"^Created preset '(?<preset>.+)' from material '(?<material>.+)'$", m => $"マテリアル '{m.Groups["material"].Value}' からプリセット '{m.Groups["preset"].Value}' を作成しました。"),
            new TranslationPattern(@"^Material parameters exported to:\n(?<path>.+)$", m => $"マテリアルパラメータを書き出しました:\n{m.Groups["path"].Value}"),
            new TranslationPattern(@"^Material parameters imported to '(?<material>.+)'$", m => $"'{m.Groups["material"].Value}' にマテリアルパラメータを読み込みました。"),
            new TranslationPattern(@"^Material '(?<material>.+)' parameters copied to clipboard\.\n\nYou can now paste these parameters to another material or share with others\.$", m => $"マテリアル '{m.Groups["material"].Value}' のパラメータをクリップボードへコピーしました。\n\nこのパラメータは別のマテリアルへ貼り付けたり、他の人へ共有したりできます。"),
            new TranslationPattern(@"^VTuber preset generation complete!\n\nPresets created: (?<count>.+)\nLocation: (?<path>.+)\n\nPresets are now displayed in this browser\.\nSelect a material and click 'Apply' to use them\.$", m => $"VTuber プリセットの生成が完了しました。\n\n作成数: {m.Groups["count"].Value}\n保存先: {m.Groups["path"].Value}\n\nプリセットはこのブラウザに表示されています。\n対象マテリアルを選択して `Apply` を押すと使えます。"),
            new TranslationPattern(@"^This scan keeps the first (?<limit>.+) issues in memory\.\nAdditional issues not stored: (?<count>.+)$", m => $"このスキャンでは最初の {m.Groups["limit"].Value} 件の問題のみをメモリに保持します。\n保持していない追加の問題数: {m.Groups["count"].Value}"),
            new TranslationPattern(@"^Warming up Natane Toon materials\.\.\.$", m => "Natane Toon マテリアルをプリウォーム中..."),
            new TranslationPattern(@"^Shader '(?<name>.+)' was not found\.$", m => $"シェーダー '{m.Groups["name"].Value}' が見つかりませんでした。")
        };

        private static readonly Dictionary<string, string> JapaneseFallbackCache = new Dictionary<string, string>(StringComparer.Ordinal);

        public static bool IsJapanese
        {
            get
            {
                if (_language < 0)
                    _language = EditorPrefs.GetInt(LANG_PREFS_KEY, 1);
                return _language == 1;
            }
        }

        public static void ToggleLanguage()
        {
            _language = IsJapanese ? 0 : 1;
            EditorPrefs.SetInt(LANG_PREFS_KEY, _language);
        }

        /// <summary>
        /// Returns ja when Japanese, en when English.
        /// When the Japanese source text was flattened to English during mojibake repair,
        /// fall back to the shared Japanese translation table.
        /// </summary>
        public static string L(string ja, string en)
        {
            if (!IsJapanese)
                return en;

            if (!NeedsJapaneseFallback(ja))
                return ja;

            string translated = TranslateJapaneseFallback(ja);
            if (!string.Equals(translated, ja, StringComparison.Ordinal))
                return translated;

            if (!string.Equals(ja, en, StringComparison.Ordinal))
            {
                translated = TranslateJapaneseFallback(en);
                if (!string.Equals(translated, en, StringComparison.Ordinal))
                    return translated;
            }

            return string.IsNullOrEmpty(ja) ? en : ja;
        }

        private static bool NeedsJapaneseFallback(string text)
        {
            if (string.IsNullOrEmpty(text))
                return true;

            return !JapaneseTextRegex.IsMatch(text) || SuspiciousLocalizedTextRegex.IsMatch(text);
        }

        private static string TranslateJapaneseFallback(string text)
        {
            string translated;
            if (string.IsNullOrEmpty(text))
                return text;

            if (JapaneseFallbackCache.TryGetValue(text, out translated))
                return translated;

            if (JapaneseFallbackExact.TryGetValue(text, out translated))
            {
                JapaneseFallbackCache[text] = translated;
                return translated;
            }

            for (int i = 0; i < JapaneseFallbackPatterns.Length; i++)
            {
                if (JapaneseFallbackPatterns[i].TryTranslate(text, out translated))
                {
                    JapaneseFallbackCache[text] = translated;
                    return translated;
                }
            }

            JapaneseFallbackCache[text] = text;
            return text;
        }

        private sealed class TranslationPattern
        {
            private readonly Regex _regex;
            private readonly Func<Match, string> _translator;

            public TranslationPattern(string pattern, Func<Match, string> translator)
            {
                _regex = new Regex(pattern, RegexOptions.Compiled | RegexOptions.CultureInvariant);
                _translator = translator;
            }

            public bool TryTranslate(string input, out string output)
            {
                Match match = _regex.Match(input);
                if (!match.Success)
                {
                    output = null;
                    return false;
                }

                output = _translator(match);
                return true;
            }
        }
    }
}
