using UnityEngine;
using UnityEditor;
using System.IO;

namespace NataneToon.Editor
{
    /// <summary>
    /// LTCGI パッケージ自動検出スクリプト
    /// Auto-detects LTCGI package and generates shader config
    ///
    /// パッケージのインストール/アンインストール時に自動でシェーダー設定を更新し、
    /// LTCGI.cginc の条件付きインクルードを制御する。
    /// </summary>
    [InitializeOnLoad]
    public static class LTCGIAutoDetector
    {
        private const string LTCGI_PACKAGE_PATH = "Packages/at.pimaker.ltcgi";
        private const string LTCGI_CGINC_PATH = "Packages/at.pimaker.ltcgi/Shaders/LTCGI.cginc";

        private static readonly string ConfigFilePath = Path.Combine(
            "Assets", "natane_engine_Toon_Shader", "Shaders", "NataneToon",
            "Include", "Config", "NataneToonLTCGIConfig.hlsl");

        private const string PREFS_KEY = "NataneToon_LTCGI_Detected";

        static LTCGIAutoDetector()
        {
            EditorApplication.delayCall += DetectAndConfigure;
        }

        public static void DetectAndConfigure()
        {
            bool isAvailable = IsPackageInstalled();
            bool wasAvailable = EditorPrefs.GetBool(PREFS_KEY, false);

            if (!File.Exists(ConfigFilePath))
            {
                WriteConfigFile(isAvailable);
                EditorPrefs.SetBool(PREFS_KEY, isAvailable);
                ReimportShaders();
                LogStatus(isAvailable, true);
                return;
            }

            if (isAvailable != wasAvailable)
            {
                WriteConfigFile(isAvailable);
                EditorPrefs.SetBool(PREFS_KEY, isAvailable);
                ReimportShaders();
                LogStatus(isAvailable, true);
            }
        }

        [MenuItem("Tools/Natane/VRChat/LTCGI 再検出 Re-detect", false, 63)]
        public static void ForceRedetect()
        {
            bool isAvailable = IsPackageInstalled();
            WriteConfigFile(isAvailable);
            EditorPrefs.SetBool(PREFS_KEY, isAvailable);
            ReimportShaders();
            LogStatus(isAvailable, true);

            string message = isAvailable
                ? "LTCGI パッケージを検出しました。\nシェーダーはLTCGI.cgincを使用します。\n\nLTCGI package detected.\nShaders will use real LTCGI functions."
                : "LTCGI パッケージが見つかりません。\nフォールバック実装（Unity SH + Reflection Probes）を使用します。\n\nLTCGI package not found.\nFallback implementation (Unity SH + Reflection Probes) will be used.";

            EditorUtility.DisplayDialog("LTCGI 検出結果", message, "OK");
        }

        public static bool IsPackageInstalled()
        {
            if (!Directory.Exists(LTCGI_PACKAGE_PATH))
                return false;
            if (!File.Exists(LTCGI_CGINC_PATH))
                return false;
            return true;
        }

        private static void WriteConfigFile(bool isAvailable)
        {
            string directory = Path.GetDirectoryName(ConfigFilePath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            string content;
            if (isAvailable)
            {
                content =
                    "// =============================================================================\n" +
                    "// NataneToon LTCGI Configuration\n" +
                    "// Auto-generated by LTCGIAutoDetector.cs\n" +
                    "// Do not edit manually - this file is regenerated when packages change\n" +
                    "// =============================================================================\n" +
                    "// LTCGI package: DETECTED\n" +
                    "// Mode: Real LTCGI (LTCGI.cginc)\n" +
                    "// =============================================================================\n" +
                    "#define NATANE_LTCGI_AVAILABLE\n";
            }
            else
            {
                content =
                    "// =============================================================================\n" +
                    "// NataneToon LTCGI Configuration\n" +
                    "// Auto-generated by LTCGIAutoDetector.cs\n" +
                    "// Do not edit manually - this file is regenerated when packages change\n" +
                    "// =============================================================================\n" +
                    "// LTCGI package: NOT DETECTED\n" +
                    "// Mode: Fallback (Unity SH + Reflection Probes)\n" +
                    "// =============================================================================\n";
            }

            File.WriteAllText(ConfigFilePath, content);
        }

        private static void ReimportShaders()
        {
            AssetDatabase.ImportAsset(ConfigFilePath, ImportAssetOptions.ForceUpdate);

            string lightingPath = Path.Combine(
                "Assets", "natane_engine_Toon_Shader", "Shaders", "NataneToon",
                "Include", "Lighting", "NataneToonLighting.hlsl");
            if (File.Exists(lightingPath))
            {
                AssetDatabase.ImportAsset(lightingPath, ImportAssetOptions.ForceUpdate);
            }

            AssetDatabase.Refresh();
        }

        private static void LogStatus(bool isAvailable, bool changed)
        {
            if (isAvailable)
            {
                Debug.Log("[NataneToon] LTCGI パッケージを検出しました。シェーダーはLTCGI.cgincを使用します。");
            }
            else if (changed)
            {
                Debug.Log("[NataneToon] LTCGI パッケージ未検出。フォールバック実装（Unity SH + Reflection Probes）を使用します。");
            }
        }
    }
}
