using UnityEngine;
using UnityEditor;
using System;
using System.IO;
using System.Text;

namespace NataneToon.Editor
{
    /// <summary>
    /// LTCGI パッケージ自動検出スクリプト
    /// Auto-detects LTCGI package and generates shader config
    ///
    /// パッケージのインストール/アンインストール時に自動でシェーダー設定を更新し、
    /// LTCGI.cginc の条件付きインクルードを制御する。
    /// </summary>
    [InitializeOnLoad]
    public static class LTCGIAutoDetector
    {
        private const string ConfigFileName = "NataneToonLTCGIConfig.hlsl";

        private const string LTCGI_PACKAGE_PATH = "Packages/at.pimaker.ltcgi";
        private const string LTCGI_CGINC_PATH = "Packages/at.pimaker.ltcgi/Shaders/LTCGI.cginc";

        private const string PREFS_KEY = "NataneToon_LTCGI_Detected";
        private static readonly UTF8Encoding Utf8WithBom = new UTF8Encoding(true);

        static LTCGIAutoDetector()
        {
            EditorApplication.delayCall += DetectAndConfigure;
        }

        public static void DetectAndConfigure()
        {
            bool isAvailable = IsPackageInstalled();
            bool wasAvailable = EditorPrefs.GetBool(PREFS_KEY, false);
            if (!TryResolvePaths(out string configAssetPath, out string configFullPath, out string lightingAssetPath))
            {
                return;
            }

            if (!File.Exists(configFullPath))
            {
                if (WriteConfigFile(configFullPath, isAvailable))
                {
                    EditorPrefs.SetBool(PREFS_KEY, isAvailable);
                    ReimportShaders(configAssetPath, lightingAssetPath);
                    LogStatus(isAvailable, true);
                }
                return;
            }

            if (isAvailable != wasAvailable)
            {
                if (WriteConfigFile(configFullPath, isAvailable))
                {
                    EditorPrefs.SetBool(PREFS_KEY, isAvailable);
                    ReimportShaders(configAssetPath, lightingAssetPath);
                    LogStatus(isAvailable, true);
                }
            }
        }

        [MenuItem("Tools/Natane/VRChat/LTCGI 再検出 Re-detect", false, 63)]
        public static void ForceRedetect()
        {
            bool isAvailable = IsPackageInstalled();
            if (!TryResolvePaths(out string configAssetPath, out string configFullPath, out string lightingAssetPath))
            {
                EditorUtility.DisplayDialog("LTCGI 検出結果", GetPathResolutionErrorMessage(), "OK");
                return;
            }

            if (!WriteConfigFile(configFullPath, isAvailable))
            {
                EditorUtility.DisplayDialog("LTCGI 検出結果", GetWriteErrorMessage(configFullPath), "OK");
                return;
            }

            EditorPrefs.SetBool(PREFS_KEY, isAvailable);
            ReimportShaders(configAssetPath, lightingAssetPath);
            LogStatus(isAvailable, true);

            string message = isAvailable
                ? "LTCGI パッケージを検出しました。\nシェーダーはLTCGI.cgincを使用します。\n\nLTCGI package detected.\nShaders will use real LTCGI functions."
                : "LTCGI パッケージが見つかりません。\nLTCGI は lilToon と同様に無効化されます。\n\nLTCGI package not found.\nLTCGI will stay disabled, matching lilToon behavior.";

            EditorUtility.DisplayDialog("LTCGI 検出結果", message, "OK");
        }

        public static bool IsPackageInstalled()
        {
            if (!AssetDatabase.IsValidFolder(LTCGI_PACKAGE_PATH))
                return false;
            if (AssetDatabase.LoadMainAssetAtPath(LTCGI_CGINC_PATH) == null)
                return false;
            return true;
        }

        private static bool WriteConfigFile(string configFullPath, bool isAvailable)
        {
            try
            {
                string directory = Path.GetDirectoryName(configFullPath);
                if (!Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                string content;
                if (isAvailable)
                {
                    content =
                        "// =============================================================================\n" +
                        "// NataneToon LTCGI Configuration\n" +
                        "// Auto-generated by LTCGIAutoDetector.cs\n" +
                        "// Do not edit manually - this file is regenerated when packages change\n" +
                        "// =============================================================================\n" +
                        "// LTCGI package: DETECTED\n" +
                        "// Mode: Real LTCGI (LTCGI.cginc)\n" +
                        "// =============================================================================\n" +
                        "#define NATANE_LTCGI_AVAILABLE\n";
                }
                else
                {
                    content =
                        "// =============================================================================\n" +
                        "// NataneToon LTCGI Configuration\n" +
                        "// Auto-generated by LTCGIAutoDetector.cs\n" +
                        "// Do not edit manually - this file is regenerated when packages change\n" +
                        "// =============================================================================\n" +
                        "// LTCGI package: NOT DETECTED\n" +
                        "// Mode: Disabled (matches lilToon package-required behavior)\n" +
                        "// =============================================================================\n";
                }

                File.WriteAllText(configFullPath, content, Utf8WithBom);
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[NataneToon] Failed to write {ConfigFileName}.\nPath: {configFullPath}\n{ex}");
                return false;
            }
        }

        private static void ReimportShaders(string configAssetPath, string lightingAssetPath)
        {
            AssetDatabase.ImportAsset(configAssetPath, ImportAssetOptions.ForceUpdate);
            if (AssetDatabase.LoadMainAssetAtPath(lightingAssetPath) != null)
            {
                AssetDatabase.ImportAsset(lightingAssetPath, ImportAssetOptions.ForceUpdate);
            }

            AssetDatabase.Refresh();
        }

        private static bool TryResolvePaths(out string configAssetPath, out string configFullPath, out string lightingAssetPath)
        {
            if (NatanePackagePathResolver.TryResolveShaderSupportPaths(
                ConfigFileName,
                out configAssetPath,
                out configFullPath,
                out lightingAssetPath))
            {
                return true;
            }

            Debug.LogError($"[NataneToon] {GetPathResolutionErrorMessage()}");
            return false;
        }

        private static string GetPathResolutionErrorMessage()
        {
            return $"Failed to resolve the Natane Toon package root while updating {ConfigFileName}.";
        }

        private static string GetWriteErrorMessage(string configFullPath)
        {
            return $"設定ファイルの更新に失敗しました。\n{configFullPath}\n\nFailed to update the config file.";
        }

        private static void LogStatus(bool isAvailable, bool changed)
        {
            if (isAvailable)
            {
                Debug.Log("[NataneToon] LTCGI パッケージを検出しました。シェーダーはLTCGI.cgincを使用します。");
            }
            else if (changed)
            {
                Debug.Log("[NataneToon] LTCGI パッケージ未検出。LTCGI は lilToon と同様に無効化されます。");
            }
        }
    }
}
