using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace NataneToon.Editor
{
    /// <summary>
    /// 正準カタログから各 .shader の Properties ブロックを生成して書き戻す。
    ///
    /// 書き換えるのは Properties { } の中身だけで、それ以外は1バイトも触らない。
    /// 改行コード(CRLF)・インデント幅・エンコーディング(UTF-8 BOM無し)は原文から検出して踏襲する。
    ///
    /// 適用前に必ず <see cref="NataneShaderPropertyCatalogBootstrap"/> の整合チェックが
    /// 合格していること。合格していない状態で走らせるとプロパティが失われる。
    /// </summary>
    internal static class NataneShaderPropertyWriter
    {
        // センチネルは「1行に1つ」。説明文を別行のコメントにすると、再パース時に
        // その行が最初の宣言の装飾行として取り込まれ、その上へ新しいヘッダーが
        // 被さって実行のたびに増殖する（実際に begin=2 まで増えた）。
        // 目印を含む行だけを読み飛ばせば冪等になるので、説明も同じ行に載せる。
        internal const string BeginMarker = "<auto-generated:natane-properties>";
        internal const string EndMarker = "</auto-generated:natane-properties>";

        internal const string BeginSentinel =
            "// " + BeginMarker + " 手編集しないでください。Tools > Natane > ビルド最適化 から再生成します。";
        internal const string EndSentinel = "// " + EndMarker;

        /// <summary>
        /// 空行数の許容減少幅。センチネル前後や除外グループ位置の余白調整で
        /// 数行のズレは生じうるが、それを超える減少は区切りの消失とみなす。
        /// </summary>
        private const int BlankLineTolerance = 4;


        // 例: "// _SOFT_FILTER, _KUWAHARA_FILTER removed (Lite variant: no GrabPass)"
        private static readonly Regex RemovalCommentRegex = new Regex(
            @"^//\s*(?<keywords>_[A-Z0-9_]+(?:\s*,\s*_[A-Z0-9_]+)*)\s+removed\s*\((?<reason>[^)]*)\)",
            RegexOptions.Compiled);

        internal sealed class ApplyResult
        {
            public string FileName;
            public bool Changed;
            public bool Written;
            public int BeforeLines;
            public int AfterLines;
            public List<string> Problems = new List<string>();
        }

        // ---- 生成 ----

        /// <summary>
        /// 1バリアント分の Properties 本文を組み立てる（外側の波括弧は含まない）。
        /// removalComments は「このシェーダーが元々持っていた除外理由コメント」。
        /// </summary>
        internal static string RenderBody(
            NataneShaderPropertyCatalog catalog,
            string shaderFileName,
            string indent,
            string newline,
            Dictionary<string, List<string>> removalCommentsByGroup)
        {
            Dictionary<string, NatanePropertyGroup> groupOf = catalog.GroupOf();

            var overrideOf = new Dictionary<string, NatanePropertyOverride>(StringComparer.Ordinal);
            foreach (NatanePropertyOverride o in catalog.Overrides)
                if (o.Shaders.Contains(shaderFileName))
                    overrideOf[o.PropertyName] = o;

            var sb = new StringBuilder();
            AppendLine(sb, indent, BeginSentinel, newline);

            var emittedRemovalFor = new HashSet<string>(StringComparer.Ordinal);

            foreach (NatanePropertyDeclaration d in catalog.Declarations)
            {
                if (!groupOf.TryGetValue(d.Name, out NatanePropertyGroup g)) continue;

                if (!g.Members.Contains(shaderFileName))
                {
                    // 除外されたグループの位置に、元の除外理由コメントを1度だけ復元する。
                    if (emittedRemovalFor.Add(g.Id) &&
                        removalCommentsByGroup != null &&
                        removalCommentsByGroup.TryGetValue(g.Id, out List<string> comments))
                    {
                        sb.Append(newline);
                        foreach (string c in comments) AppendLine(sb, indent, c, newline);
                    }
                    continue;
                }

                // 装飾行はバリアント自身のものを優先する。バリアントごとに
                // セクション見出しの付け方が異なるため、正準側で上書きすると失われる。
                foreach (string lead in catalog.DecorationFor(shaderFileName, d.Name, d.LeadingLines))
                    AppendLine(sb, indent, lead, newline);

                string declLine = overrideOf.TryGetValue(d.Name, out NatanePropertyOverride ov) && ov.Declaration != null
                    ? ov.Declaration.Line
                    : d.Line;

                AppendLine(sb, indent, declLine, newline);
            }

            sb.Append(newline);
            AppendLine(sb, indent, EndSentinel, newline);

            return sb.ToString();
        }

        private static void AppendLine(StringBuilder sb, string indent, string content, string newline)
        {
            if (content.Length == 0) sb.Append(newline);
            else sb.Append(indent).Append(content).Append(newline);
        }

        // ---- 適用 ----

        /// <summary>
        /// 1バリアントへ適用する。dryRun なら書き込まず差分だけ返す。
        /// 生成結果を再解析して宣言集合とコメント数が保たれているかを必ず検査し、
        /// 崩れていれば書き込まない。
        /// </summary>
        /// <param name="allowedNewProperties">
        /// 意図して増やすプロパティ名（追加定義から合流させたもの）。
        /// これを渡さないと、新機能の追加が「生成器が勝手に宣言を増やした」と
        /// 判定されて書き込みが拒否される。安全検査は
        /// 「生成器の暴走」と「運用者の宣言」を区別できる必要がある。
        /// </param>
        internal static ApplyResult Apply(
            NataneToonVariantLocator.Entry entry,
            NataneShaderPropertyCatalog catalog,
            bool dryRun,
            IReadOnlyCollection<string> allowedNewProperties = null)
        {
            var allowed = allowedNewProperties == null
                ? new HashSet<string>(StringComparer.Ordinal)
                : new HashSet<string>(allowedNewProperties, StringComparer.Ordinal);

            var result = new ApplyResult { FileName = entry.FileName };

            string source = entry.Source;
            if (!NatanePropertyParser.TryLocatePropertiesBlock(source, out int bodyStart, out int bodyLength))
            {
                result.Problems.Add("Properties ブロックを特定できませんでした");
                return result;
            }

            string originalBody = source.Substring(bodyStart, bodyLength);
            string newline = source.Contains("\r\n") ? "\r\n" : "\n";
            string indent = DetectIndent(originalBody);

            Dictionary<string, List<string>> removalByGroup = CollectRemovalComments(originalBody, catalog);

            string generated = RenderBody(catalog, entry.FileName, indent, newline, removalByGroup);
            string newBody = newline + generated + IndentOnly(source, bodyStart);

            result.BeforeLines = CountLines(originalBody);
            result.AfterLines = CountLines(newBody);

            string newSource = source.Substring(0, bodyStart) + newBody + source.Substring(bodyStart + bodyLength);
            result.Changed = !string.Equals(newSource, source, StringComparison.Ordinal);

            // --- 生成物の自己検査（ここが通らなければ絶対に書かない）---
            List<NatanePropertyDeclaration> before =
                NatanePropertyParser.ParseBlockText(originalBody, out List<string> beforeUnparsed);
            List<NatanePropertyDeclaration> after =
                NatanePropertyParser.ParseBlockText(newBody, out List<string> afterUnparsed);

            var beforeKeys = new HashSet<string>(before.Select(d => d.SignatureKey), StringComparer.Ordinal);
            var afterKeys = new HashSet<string>(after.Select(d => d.SignatureKey), StringComparer.Ordinal);

            // 消失はいかなる場合も許さない。
            foreach (string lost in beforeKeys.Except(afterKeys, StringComparer.Ordinal).OrderBy(x => x, StringComparer.Ordinal))
                result.Problems.Add("生成で消えた宣言: " + lost);

            // 増加は「追加定義で宣言したもの」だけ許す。
            foreach (NatanePropertyDeclaration d in after
                         .Where(d => !beforeKeys.Contains(d.SignatureKey))
                         .OrderBy(d => d.Name, StringComparer.Ordinal))
            {
                if (allowed.Contains(d.Name)) continue;
                result.Problems.Add("生成で増えた宣言: " + d.SignatureKey);
            }

            if (afterUnparsed.Count > 0)
                result.Problems.Add($"生成結果に解釈できない行が {afterUnparsed.Count} 件（{afterUnparsed[0]}）");
            if (beforeUnparsed.Count > 0)
                result.Problems.Add($"元ソースに解釈できない行が {beforeUnparsed.Count} 件（{beforeUnparsed[0]}）");

            int beforeComments = CountCommentLines(originalBody);
            int afterComments = CountCommentLines(newBody);
            // センチネル3行ぶんは生成で増える。それ以外の減少は情報損失とみなす。
            if (afterComments < beforeComments)
                result.Problems.Add($"コメント行が減少: {beforeComments} -> {afterComments}");

            // 空行はセクション区切りとして意味を持つ。宣言が消えないため
            // SignatureKey 比較では検出できないので、ここで別途見る。
            // （実際、当初の実装では Lite 1本で 59 行の空行が黙って消えていた）
            int beforeBlanks = CountBlankLines(originalBody);
            int afterBlanks = CountBlankLines(newBody);
            if (afterBlanks + BlankLineTolerance < beforeBlanks)
            {
                result.Problems.Add(
                    $"空行が減少: {beforeBlanks} -> {afterBlanks}（セクション区切りが失われている）");
            }

            // 冪等性。生成物にセンチネルが2つ以上あるなら、前回のセンチネルを
            // 取り込んだうえに新しいものを積んでいる（実行のたびに増える状態）。
            int beginCount = CountOccurrences(newBody, BeginMarker);
            int endCount = CountOccurrences(newBody, EndMarker);
            if (beginCount != 1 || endCount != 1)
            {
                result.Problems.Add(
                    $"センチネルが重複: 開始 {beginCount} / 終了 {endCount}（生成が冪等でない）");
            }

            if (result.Problems.Count > 0 || dryRun || !result.Changed) return result;

            try
            {
                File.WriteAllText(entry.FullPath, newSource, new UTF8Encoding(false));
                result.Written = true;
            }
            catch (Exception e)
            {
                result.Problems.Add("書き込み失敗: " + e.Message);
            }

            return result;
        }

        // ---- 補助 ----

        /// <summary>本文の最初の非空行からインデント幅を推定する（既定は空白8）。</summary>
        private static string DetectIndent(string body)
        {
            foreach (string raw in body.Split('\n'))
            {
                string line = raw.TrimEnd('\r');
                if (line.Trim().Length == 0) continue;

                int n = 0;
                while (n < line.Length && (line[n] == ' ' || line[n] == '\t')) n++;
                if (n > 0) return line.Substring(0, n);
            }
            return new string(' ', 8);
        }

        /// <summary>閉じ波括弧の直前に置くインデント（Properties の閉じ括弧行に合わせる）。</summary>
        private static string IndentOnly(string source, int bodyStart)
        {
            // "    Properties" の行頭インデントを再利用する。
            int lineStart = source.LastIndexOf('\n', Math.Max(0, bodyStart - 1)) + 1;
            int n = lineStart;
            while (n < source.Length && (source[n] == ' ' || source[n] == '\t')) n++;
            return source.Substring(lineStart, n - lineStart);
        }

        /// <summary>
        /// 元ソースの除外理由コメントを採否グループへ割り当てる。
        /// コメントが名指しするキーワードから対応するトグルプロパティを引き、
        /// そのプロパティが属するグループに結び付ける。
        /// </summary>
        private static Dictionary<string, List<string>> CollectRemovalComments(
            string body, NataneShaderPropertyCatalog catalog)
        {
            var keywordToProperty = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var mapping in NataneShaderKeywordSynchronizer.KeywordMappings)
                if (!string.IsNullOrEmpty(mapping.keyword) && !keywordToProperty.ContainsKey(mapping.keyword))
                    keywordToProperty[mapping.keyword] = mapping.propertyName;

            Dictionary<string, NatanePropertyGroup> groupOf = catalog.GroupOf();
            var result = new Dictionary<string, List<string>>(StringComparer.Ordinal);

            foreach (string raw in body.Split('\n'))
            {
                string line = raw.TrimEnd('\r').Trim();
                Match m = RemovalCommentRegex.Match(line);
                if (!m.Success) continue;

                foreach (string kw in m.Groups["keywords"].Value.Split(',').Select(s => s.Trim()))
                {
                    if (!keywordToProperty.TryGetValue(kw, out string prop)) continue;
                    if (!groupOf.TryGetValue(prop, out NatanePropertyGroup g)) continue;

                    if (!result.TryGetValue(g.Id, out List<string> list))
                    {
                        list = new List<string>();
                        result[g.Id] = list;
                    }
                    if (!list.Contains(line)) list.Add(line);
                    break; // 1コメント = 1グループへの割り当てで十分
                }
            }

            return result;
        }

        private static int CountLines(string s)
        {
            if (string.IsNullOrEmpty(s)) return 0;
            return s.Split('\n').Length;
        }

        private static int CountCommentLines(string s)
        {
            return s.Split('\n').Count(l => l.TrimStart().StartsWith("//", StringComparison.Ordinal));
        }

        private static int CountBlankLines(string s)
        {
            return s.Split('\n').Count(l => l.Trim().Length == 0);
        }

        private static int CountOccurrences(string haystack, string needle)
        {
            int count = 0;
            int i = 0;
            while (true)
            {
                int hit = haystack.IndexOf(needle, i, StringComparison.Ordinal);
                if (hit < 0) return count;
                count++;
                i = hit + needle.Length;
            }
        }
    }
}
