using UnityEngine;
using UnityEditor;
using System.IO;

namespace NataneToon.Editor
{
    /// <summary>
    /// VRC Light Volumes パッケージ自動検出スクリプト
    /// Auto-detects VRC Light Volumes package and generates shader config
    ///
    /// パッケージのインストール/アンインストール時に自動でシェーダー設定を更新し、
    /// LightVolumes.cginc の条件付きインクルードを制御する。
    /// </summary>
    [InitializeOnLoad]
    public static class VRCLightVolumesAutoDetector
    {
        // Path to the VRC Light Volumes package
        private const string VRCLV_PACKAGE_PATH = "Packages/red.sim.lightvolumes";
        private const string VRCLV_CGINC_PATH = "Packages/red.sim.lightvolumes/Shaders/LightVolumes.cginc";

        // Path to the auto-generated config file (relative to project root)
        private static readonly string ConfigFilePath = Path.Combine(
            "Assets", "natane_engine_Toon_Shader", "Shaders", "NataneToon",
            "Include", "Config", "NataneToonLVConfig.hlsl");

        // EditorPrefs key to track last known state
        private const string PREFS_KEY = "NataneToon_VRCLV_Detected";

        static VRCLightVolumesAutoDetector()
        {
            // Run detection on domain reload (covers editor startup, package install/uninstall, script recompile)
            EditorApplication.delayCall += DetectAndConfigure;
        }

        /// <summary>
        /// Detect VRC Light Volumes package and update shader config
        /// </summary>
        public static void DetectAndConfigure()
        {
            bool isAvailable = IsPackageInstalled();
            bool wasAvailable = EditorPrefs.GetBool(PREFS_KEY, false);

            // Always ensure config file exists
            if (!File.Exists(ConfigFilePath))
            {
                WriteConfigFile(isAvailable);
                EditorPrefs.SetBool(PREFS_KEY, isAvailable);
                ReimportShaders();
                LogStatus(isAvailable, true);
                return;
            }

            // Only update if state changed
            if (isAvailable != wasAvailable)
            {
                WriteConfigFile(isAvailable);
                EditorPrefs.SetBool(PREFS_KEY, isAvailable);
                ReimportShaders();
                LogStatus(isAvailable, true);
            }
        }

        /// <summary>
        /// Force re-detection (callable from menu)
        /// </summary>
        [MenuItem("Tools/Natane/VRChat/VRC Light Volumes 再検出 Re-detect", false, 62)]
        public static void ForceRedetect()
        {
            bool isAvailable = IsPackageInstalled();
            WriteConfigFile(isAvailable);
            EditorPrefs.SetBool(PREFS_KEY, isAvailable);
            ReimportShaders();
            LogStatus(isAvailable, true);

            string message = isAvailable
                ? "VRC Light Volumes パッケージを検出しました。\nシェーダーは本物のLight Volumes関数を使用します。\n\nVRC Light Volumes package detected.\nShaders will use real Light Volumes functions."
                : "VRC Light Volumes パッケージが見つかりません。\nシェーダーはバンドル版LightVolumes.cgincを使用します。\n\nVRC Light Volumes package not found.\nShaders will use bundled LightVolumes.cginc.";

            EditorUtility.DisplayDialog("VRC Light Volumes 検出結果", message, "OK");
        }

        /// <summary>
        /// Check if VRC Light Volumes package is installed
        /// </summary>
        public static bool IsPackageInstalled()
        {
            // Check for the package directory
            if (!Directory.Exists(VRCLV_PACKAGE_PATH))
                return false;

            // Verify the cginc file exists
            if (!File.Exists(VRCLV_CGINC_PATH))
                return false;

            return true;
        }

        /// <summary>
        /// Write the shader config file
        /// </summary>
        private static void WriteConfigFile(bool isAvailable)
        {
            // Ensure directory exists
            string directory = Path.GetDirectoryName(ConfigFilePath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            string content;
            if (isAvailable)
            {
                content =
                    "// =============================================================================\n" +
                    "// NataneToon VRC Light Volumes Configuration\n" +
                    "// Auto-generated by VRCLightVolumesAutoDetector.cs\n" +
                    "// Do not edit manually - this file is regenerated when packages change\n" +
                    "// =============================================================================\n" +
                    "// VRC Light Volumes package: DETECTED\n" +
                    "// Mode: Real VRC Light Volumes (LightVolumes.cginc)\n" +
                    "// =============================================================================\n" +
                    "#define NATANE_VRCLV_AVAILABLE\n";
            }
            else
            {
                content =
                    "// =============================================================================\n" +
                    "// NataneToon VRC Light Volumes Configuration\n" +
                    "// Auto-generated by VRCLightVolumesAutoDetector.cs\n" +
                    "// Do not edit manually - this file is regenerated when packages change\n" +
                    "// =============================================================================\n" +
                    "// VRC Light Volumes package: NOT DETECTED\n" +
                    "// Mode: Bundled LightVolumes.cginc\n" +
                    "// =============================================================================\n";
            }

            File.WriteAllText(ConfigFilePath, content);
        }

        /// <summary>
        /// Reimport shaders to pick up config changes
        /// </summary>
        private static void ReimportShaders()
        {
            AssetDatabase.ImportAsset(ConfigFilePath, ImportAssetOptions.ForceUpdate);

            // Reimport the lighting hlsl that includes the config
            string lightingPath = Path.Combine(
                "Assets", "natane_engine_Toon_Shader", "Shaders", "NataneToon",
                "Include", "Lighting", "NataneToonLighting.hlsl");
            if (File.Exists(lightingPath))
            {
                AssetDatabase.ImportAsset(lightingPath, ImportAssetOptions.ForceUpdate);
            }

            AssetDatabase.Refresh();
        }

        private static void LogStatus(bool isAvailable, bool changed)
        {
            if (isAvailable)
            {
                Debug.Log("[NataneToon] VRC Light Volumes パッケージを検出しました。シェーダーはLightVolumes.cgincを使用します。");
            }
            else if (changed)
            {
                Debug.Log("[NataneToon] VRC Light Volumes パッケージ未検出。バンドル版LightVolumes.cgincを使用します。");
            }
        }
    }
}
