using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace NataneToon.Editor
{
    /// <summary>
    /// Auto-detects the VRC Light Volumes package and generates shader config.
    /// Updates the shader config when the package is installed or removed and
    /// switches LightVolumes.cginc between the package path and the bundled path.
    /// </summary>
    [InitializeOnLoad]
    public static class VRCLightVolumesAutoDetector
    {
        private const string ConfigFileName = "NataneToonLVConfig.hlsl";
        private const string VRCLV_PACKAGE_PATH = "Packages/red.sim.lightvolumes";
        private const string VRCLV_CGINC_PATH = "Packages/red.sim.lightvolumes/Shaders/LightVolumes.cginc";
        private const string PREFS_KEY = "NataneToon_VRCLV_Detected";
        private static readonly UTF8Encoding Utf8WithBom = new UTF8Encoding(true);

        static VRCLightVolumesAutoDetector()
        {
            EditorApplication.delayCall += DetectAndConfigure;
        }

        public static void DetectAndConfigure()
        {
            bool isAvailable = IsPackageInstalled();
            bool wasAvailable = EditorPrefs.GetBool(PREFS_KEY, false);
            if (!TryResolvePaths(out string configAssetPath, out string configFullPath, out string lightingAssetPath))
            {
                return;
            }

            if (!File.Exists(configFullPath))
            {
                if (WriteConfigFile(configFullPath, isAvailable))
                {
                    EditorPrefs.SetBool(PREFS_KEY, isAvailable);
                    ReimportShaders(configAssetPath, lightingAssetPath);
                    LogStatus(isAvailable, true);
                }

                return;
            }

            if (isAvailable != wasAvailable)
            {
                if (WriteConfigFile(configFullPath, isAvailable))
                {
                    EditorPrefs.SetBool(PREFS_KEY, isAvailable);
                    ReimportShaders(configAssetPath, lightingAssetPath);
                    LogStatus(isAvailable, true);
                }
            }
        }

        [MenuItem("Tools/Natane/VRChat/VRC Light Volumes Re-detect", false, 62)]
        public static void ForceRedetect()
        {
            bool isAvailable = IsPackageInstalled();
            if (!TryResolvePaths(out string configAssetPath, out string configFullPath, out string lightingAssetPath))
            {
                EditorUtility.DisplayDialog("VRC Light Volumes Detection", GetPathResolutionErrorMessage(), "OK");
                return;
            }

            if (!WriteConfigFile(configFullPath, isAvailable))
            {
                EditorUtility.DisplayDialog("VRC Light Volumes Detection", GetWriteErrorMessage(configFullPath), "OK");
                return;
            }

            EditorPrefs.SetBool(PREFS_KEY, isAvailable);
            ReimportShaders(configAssetPath, lightingAssetPath);
            LogStatus(isAvailable, true);

            string message = isAvailable
                ? "VRC Light Volumes package detected.\nShaders will use the package LightVolumes.cginc."
                : "VRC Light Volumes package not found.\nShaders will use the bundled LightVolumes.cginc.";

            EditorUtility.DisplayDialog("VRC Light Volumes Detection", message, "OK");
        }

        public static bool IsPackageInstalled()
        {
            if (!AssetDatabase.IsValidFolder(VRCLV_PACKAGE_PATH))
            {
                return false;
            }

            return AssetDatabase.LoadMainAssetAtPath(VRCLV_CGINC_PATH) != null;
        }

        private static bool WriteConfigFile(string configFullPath, bool isAvailable)
        {
            try
            {
                string directory = Path.GetDirectoryName(configFullPath);
                if (!Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                string content = isAvailable
                    ? "// =============================================================================\n" +
                      "// NataneToon VRC Light Volumes Configuration\n" +
                      "// Auto-generated by VRCLightVolumesAutoDetector.cs\n" +
                      "// Do not edit manually - this file is regenerated when packages change\n" +
                      "// =============================================================================\n" +
                      "// VRC Light Volumes package: DETECTED\n" +
                      "// Mode: Real VRC Light Volumes (LightVolumes.cginc)\n" +
                      "// =============================================================================\n" +
                      "#define NATANE_VRCLV_AVAILABLE\n"
                    : "// =============================================================================\n" +
                      "// NataneToon VRC Light Volumes Configuration\n" +
                      "// Auto-generated by VRCLightVolumesAutoDetector.cs\n" +
                      "// Do not edit manually - this file is regenerated when packages change\n" +
                      "// =============================================================================\n" +
                      "// VRC Light Volumes package: NOT DETECTED\n" +
                      "// Mode: Bundled LightVolumes.cginc\n" +
                      "// =============================================================================\n";

                File.WriteAllText(configFullPath, content, Utf8WithBom);
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[NataneToon] Failed to write {ConfigFileName}.\nPath: {configFullPath}\n{ex}");
                return false;
            }
        }

        private static void ReimportShaders(string configAssetPath, string lightingAssetPath)
        {
            AssetDatabase.ImportAsset(configAssetPath, ImportAssetOptions.ForceUpdate);

            if (AssetDatabase.LoadMainAssetAtPath(lightingAssetPath) != null)
            {
                AssetDatabase.ImportAsset(lightingAssetPath, ImportAssetOptions.ForceUpdate);
            }

            AssetDatabase.Refresh();
        }

        private static bool TryResolvePaths(out string configAssetPath, out string configFullPath, out string lightingAssetPath)
        {
            if (NatanePackagePathResolver.TryResolveShaderSupportPaths(
                ConfigFileName,
                out configAssetPath,
                out configFullPath,
                out lightingAssetPath))
            {
                return true;
            }

            Debug.LogError($"[NataneToon] {GetPathResolutionErrorMessage()}");
            return false;
        }

        private static string GetPathResolutionErrorMessage()
        {
            return $"Failed to resolve the Natane Toon package root while updating {ConfigFileName}.";
        }

        private static string GetWriteErrorMessage(string configFullPath)
        {
            return $"Failed to update the config file.\n{configFullPath}";
        }

        private static void LogStatus(bool isAvailable, bool changed)
        {
            if (isAvailable)
            {
                Debug.Log("[NataneToon] VRC Light Volumes package detected. Using the package LightVolumes.cginc.");
            }
            else if (changed)
            {
                Debug.Log("[NataneToon] VRC Light Volumes package not found. Using the bundled LightVolumes.cginc.");
            }
        }
    }
}
