// =============================================================================
// NataneToon VRC Light Volumes Configuration
// Auto-generated by VRCLightVolumesAutoDetector.cs
// Do not edit manually - this file is regenerated when packages change
// =============================================================================
// VRC Light Volumes package: NOT DETECTED
// Mode: Fallback (Unity Light Probes)
// =============================================================================
