// =============================================================================
// NataneToon LTCGI Configuration
// Auto-generated by LTCGIAutoDetector.cs
// Do not edit manually - this file is regenerated when packages change
// =============================================================================
// LTCGI package: NOT DETECTED
// Mode: Disabled (matches lilToon package-required behavior)
// =============================================================================
